### ISSUE TITLE
Funding links in badgets

### ISSUE THREAD

**Issue by jesusalberto18** [Envoy-VC/awesome-badges#25]
Hello @Envoy-VC,

I have a question about the badgets, I want to add fund badgets to my readme, how can I link a badget to any of my accounts? Specifically:

- Paypal.
- Payoneer.
- Stripe.
- Bank account.

Thank for your help...

**Comment by Envoy-VC** [comment]
For instance, if you wish to receive payments through PayPal, you may go to [PayPal.Me](https://www.paypal.com/in/webapps/mpp/paypal-me), register a link for yourself, and then wrap that link around a badge. For Example:

```md
<a href="https://www.paypal.com/paypalme/envoy1084">
<img src="https://img.shields.io/badge/PayPal-00457C?style=for-the-badge&logo=paypal&logoColor=white" />
</a>
```

<a href="https://www.paypal.com/paypalme/envoy1084">
<img src="https://img.shields.io/badge/PayPal-00457C?style=for-the-badge&logo=paypal&logoColor=white" />
</a>

<br>

Therefore, clicking the badge will bring you to your PayPal website where you can send payment.

**Comment by Envoy-VC** [comment]
> Hello @Envoy-VC,
> 
> I have a question about the badgets, I want to add fund badgets to my readme, how can I link a badget to any of my accounts? Specifically:
> 
> * Paypal.
> * Payoneer.
> * Stripe.
> * Bank account.
> 
> Thank for your help...

For instance, if you wish to receive payments through PayPal, you may go to [PayPal.Me](https://www.paypal.com/in/webapps/mpp/paypal-me), register a link for yourself, and then wrap that link around a badge. For Example:

```md
<a href="https://www.paypal.com/paypalme/envoy1084">
<img src="https://img.shields.io/badge/PayPal-00457C?style=for-the-badge&logo=paypal&logoColor=white" />
</a>
```

<a href="https://www.paypal.com/paypalme/envoy1084">
<img src="https://img.shields.io/badge/PayPal-00457C?style=for-the-badge&logo=paypal&logoColor=white" />
</a>

<br>

Therefore, clicking the badge will bring you to your PayPal website where you can send payment.

**Comment by jesusalberto18** [comment]
Thank you for your answer @Envoy-VC,

It was very helpful, I will proceed to close this issue.
