### ISSUE TITLE
[New Badge Request] Castbox Badge Request

### ISSUE THREAD

**Issue by lnxpy** [Envoy-VC/awesome-badges#31]
- Badge name - Castbox
- Category - Sound
- URL - https://castbox.fm/

**Comment by Envoy-VC** [comment]
hey @lnxpy it's done

https://github.com/Envoy-VC/awesome-badges/commit/3c2a0a84b4649b2c98d1118fe6f1b3081a19935c

**Comment by lnxpy** [comment]
@Envoy-VC Thanks!
