### ISSUE TITLE
[Badge Request] - Astro

### ISSUE THREAD

**Issue by Hopelezz** [Envoy-VC/awesome-badges#6]
- Badge name - {ASTRO}
- Category - {Frameworks, Platforms and Libraries}

[Astro Website](https://astro.build/)

[Brand Files](https://github.com/withastro/astro/tree/main/assets/brand)

**Comment by Envoy-VC** [comment]
added Astro Badge in [Other](https://github.com/Envoy-VC/awesome-badges#-other) Category
